- hosts: 47.52.230.165
  remote_user: root
  tasks:
  - name: Print Host Name
    debug: msg={{  ansible_nodename  }}
  - name: Install epel-release
    yum: 
     name: epel-release 
     state: present
  - name: Install pip
    yum: 
     name: python-pip 
     state: present
  - name: Install docker-py 
    pip:
      name: docker-py
  - name: Get docker-ce.repo
    get_url: url=https://download.docker.com/linux/centos/docker-ce.repo dest=/etc/yum.repos.d/docker-ce.repo
  - name: Install Docker
    yum: 
     name: "{{item}}" 
     state: present
     update_cache: yes
    with_items:
     - yum-utils
     - device-mapper-persistent-data
     - lvm2
     - containerd.io
     - docker-ce-cli
     - docker-ce
  - name: Start Docker Service
    service: 
     name: docker 
     state: started
  - name: Pull An Java Image version=1.8.0_162
    docker:
     image: qq79428316/club-java:1.8.0_162
     pull: always
  - name: Stop Jave Container
    uri:
     url: http://{{ ansible_default_ipv4.address }}/actuator/shutdown
     method: POST
    ignore_errors: yes
  - name: Wait For Java Container Down
    wait_for:
     port: 80
     state: stopped
  - name: Remove Java Container
    docker_container:
     name: "{{ lookup('env','JOB_NAME') }}"
     state: absent
  - name: Send Jar File
    copy: src=/mnt/workspace/{{ lookup('env','JOB_NAME') }}/{{ lookup('env','GIT_NAME') }}/target/eureka-server-1.0.0.jar dest=/data/java/
  - name: Run A Java Container
    docker_container:
     name: "{{ lookup('env','JOB_NAME') }}"
     image: qq79428316/club-java:1.8.0_162
     network_mode: host
     volumes:
       - "/data/java:/mnt"
     command: java -server -jar /mnt/eureka-server-1.0.0.jar --spring.profiles.active=dev_cluster1
  - name: Wait For Java Container Up
    wait_for:
     port: 80
     state: started
     timeout: 600
  - name: Get Service Status
    uri:
     url: http://47.52.230.165
  - name: Print Service Status
    debug: msg="UP"
