version: '3'
services:
        jenkins:
                image: jenkinsci/blueocean
                container_name: jenkins
                user: root
                restart: always
                volumes:
                 - "/data/jenkins/data:/var/jenkins_home"
                 - "/var/run/docker.sock:/var/run/docker.sock"
                 - "/etc/localtime:/etc/localtime"
                network_mode: "host"
