---
- name: Ansible Deploy demo-kefu-java-task.yml
  vars:
    host: "{{ lookup('env','JOB_NAME') }}"
    jar_path: "{{ lookup('env','WORKSPACE') }}/{{ lookup('env','jar_path') }}"
    jar_name: "{{ lookup('env','jar_name') }}"
    jar_base_name: "{{ lookup('env','jar_base_name') }}"
    spring_profiles: "{{ lookup('env','spring_profiles') }}"
    java_version: "{{ lookup('env','docker_java_version') }}"
  hosts: "{{ host }}"
  remote_user: root
  # gather_facts: false
  any_errors_fatal: true
  serial: 1

  tasks:
  - name: Print Host Name
    debug:
      msg: "{{ ansible_hostname }}"
  
  - name: Install epel-release
    yum:
      name: 
        - epel-release

  - name: Install JQ and Pip and glances
    yum:
      name: 
        - jq
        - python-pip
        - glances

  - name: Install docker-py
    pip:
      name: docker-py

  - name: "Pull an Java Image version = {{ java_version }}"
    docker_image:
      name: "qq79428316/club-java:{{ java_version }}"
      http_timeout: 300
    register: result
    until: result | success
    retries: 20
    delay: 5

  - name: Gracefully Halting 
    uri:
      url: "http://127.0.0.1/actuator/shutdown"
      method: POST
      return_content: yes
      status_code: 200
    register: shutdown_stats
    until: shutdown_stats.status is defined and shutdown_stats.status == 200
    retries: 2
    delay: 5
    ignore_errors: yes

  - name: Wait for java container down
    wait_for: 
      port: 80
      state: stopped
      timeout: 120
      msg: 80 Port stop failed of the 120 seconds
    ignore_errors: yes

  - name: Print Gracefully Halting Status
    debug:
      msg: "{{ shutdown_stats }}"
    ignore_errors: yes

  - name: Remove All Java Container
    docker:
      image: "qq79428316/club-java:{{ java_version }}"
      state: absent

  - name: Send jar file
    copy:
      src: "{{ jar_path }}"
      dest: /data/usr-data

  - name: Start Java Container
    docker_container:
      name: "{{ ansible_hostname }}"
      image: "qq79428316/club-java:{{ java_version }}"
      network_mode: host
      restart_policy: always
      state: started
      log_driver: json-file
      log_options:
        max-size: 100m
        max-file: "5"
      volumes:
        - /data/usr-data:/data/usr-data
      command: java -server -jar
                  /data/usr-data/{{ jar_name }}
                  --spring.profiles.active={{ spring_profiles }}

  - name: Wait for java container up
    wait_for: 
      port: 80
      timeout: 120
      msg: 80 Port startup failed of the 120 seconds

  - name: Get Service Status
    shell: "curl http://127.0.0.1/actuator/health | jq .status"
    register: service_stats
    until: service_stats.stdout.find("UP") != -1
    retries: 15
    delay: 30

  - name: Print Service Status
    debug:
      msg: "{{ service_stats.stdout  }}"

  - name: Send Jstatd Config file
    copy:
      src: /data/ansible/java/jstatd.policy
      dest: /data/usr-data/jstatd.policy

  - name: Run Jstatd
    shell: "docker exec {{ ansible_hostname }} nohup jstatd -p10003 -J-Djava.security.policy=/data/usr-data/jstatd.policy &"

  - name: Wait for Jstatd up
    wait_for: 
      port: 10003
      timeout: 120
      msg: 10003 Port startup failed of the 120 seconds

  - name: Sleep 20 to next
    shell: "sleep 20"


      
