---
- name: Ansible Deploy dev-node-task.yml
  vars:
    host: "{{ lookup('env','JOB_NAME') }}"
    work_path: "{{ lookup('env','WORKSPACE') }}"
    package_name: "{{ lookup('env','JOB_NAME') }}"
    project_path: "{{ lookup('env','project_path') }}"
  hosts: "{{ host }}"
  remote_user: root
  gather_facts: false
  any_errors_fatal: false

  tasks:
  - name: Install Rsync
    yum:
      name: rsync

  - name: Create project directory
    file:
      path: "{{ project_path }}"
      state: directory

  - name: Create tmp directory
    file:
      path: "/root/tmp/{{ package_name }}"
      state: directory

  - name: Send Project Package {{ package_name }}.tar.gz
    unarchive:
      src: "{{ work_path }}/dist/{{ package_name }}.tar.gz"
      dest: "/root/tmp/{{ package_name }}"
      owner: root
      group: root

  - name: Rsync Code
    shell: "rsync -av --delete /root/tmp/{{ package_name }}/ {{ project_path }}"
    register: rsync_stats

  - name: Print Rsync Status
    debug:
      msg: "{{ rsync_stats.stdout_lines }}"

  - name: Remove tmp directory
    file:
      path: "/root/tmp/{{ package_name }}"
      state: absent