---
- name: Ansible Deploy install-fluentd-client.yml
  hosts: test-mdw-prometheus
  remote_user: root
  any_errors_fatal: true
  gather_facts: false
  vars:
    fluentd_version: v1.2.6
    fluentd_config: prod-fluent-client.conf

  tasks:
  - name: Install epel-release
    yum:
      name: 
        - epel-release

  - name: Install JQ and Pip and glances
    yum:
      name: 
        - jq
        - python-pip
        - glances

  - name: Install docker-py
    pip:
      name: docker-py

  - name: Chmod Docker Sock 
    file:
      path: /var/run/docker.sock
      mode: 0666

  - name: Pull an Fluentd Image
    docker_image:
      name: "fluent/fluentd:{{ fluentd_version }}"
      http_timeout: 300
    register: result
    until: result | success
    retries: 20
    delay: 5

  - name: Create Fluentd Config Directory
    file:
      path: /data/usr-data/fluentd
      state: directory

  - name: Send Fluentd Config file
    copy:
      src: "/data/ansible/fluentd/{{ fluentd_config }}"
      dest: /data/usr-data/fluentd/fluent-client.conf

  - name: Start Fluentd Client
    docker_container:
      name: "fluentd-client"
      image: "fluent/fluentd:{{ fluentd_version }}"
      network_mode: host
      restart_policy: always
      state: started
      recreate: yes
      volumes:
        - /data/usr-data/fluentd/fluent-client.conf:/fluentd/etc/fluent.conf
        - /etc/localtime:/etc/localtime

  - name: Wait for fluentd container up
    wait_for: 
      port: 24224
      timeout: 120
      msg: 24224 Port startup failed of the 120 seconds



