---
- name: Ansible Deploy test-kefu-node.yml
  vars:
   host: "{{ lookup('env','JOB_NAME') }}"
   job_name: "{{ lookup('env','JOB_NAME') }}"
   package_name: "{{lookup('env','JOB_NAME') }}"
   project_path: "{{lookup('env','project_path')}}"
  hosts: "{{host}}"
  remote_user: root
  tasks:
   - name: Install Rsync
     yum:
      name: rsync
      state: present
   - name: Create project directory
     file:
      path: "{{project_path}}"
      state: directory
   - name: Create Temp directory
     file:
      path: "/tmp/{{project_path}}"
      state: directory
   - name: Sent project package
     unarchive:
      src: "/data/workspace/{{job_name}}/dist/{{package_name}}.tar.gz"
      dest: "/tmp/{{project_path}}"
   - name: Rsync code
     shell: "rsync -av --delete /tmp/{{project_path}}/ {{project_path}}"
     register: rsyncresult
   - name: Print rsync status
     debug:
      msg: "{{rsyncresult.stdout_lines}}"
   - name: Remove tmp directory
     file:
      path: /tmp/tmpdirectory
      state: absent

